-- BEGIN TRANSACTION;
-- commit;
-- 목데이터 링크
-- https://www.mockaroo.com
CREATE TABLE tb_pet (
    owner_id varchar(100) not null primary key,
    name varchar(100),
    type varchar(50) ,
    fur_color varchar(100),
    age int ,
    body_build varchar(100),
);

CREATE TABLE tb_owner (
  id varchar(100) not null primary key,
  name varchar(100),
  tel varchar(100),
  address varchar(100)
);

insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.statcounter.Domainer', 'House sparrow', 'jcb', 'Turquoise', 1, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('uk.co.independent.Tin', 'Mockingbird, galapagos', 'laser', 'Purple', 2, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.sciencedaily.Tresom', 'Pale-throated three-toed sloth', 'diners-club-carte-blanche', 'Violet', 3, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.reddit.Rank', 'Dog, black-tailed prairie', 'bankcard', 'Indigo', 4, 'americanexpress');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('io.pen.Ventosanzap', 'Trumpeter, green-winged', 'jcb', 'Khaki', 5, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('jp.i2i.Job', 'Swainson''s francolin', 'diners-club-enroute', 'Khaki', 6, 'maestro');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('net.php.Greenlam', 'Skimmer, four-spotted', 'laser', 'Blue', 7, 'maestro');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.squidoo.Y-find', 'White-rumped vulture', 'maestro', 'Indigo', 8, 'bankcard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('cn.gov.miitbeian.Fintone', 'Squirrel glider', 'jcb', 'Khaki', 9, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.hexun.Veribet', 'Goanna lizard', 'laser', 'Indigo', 10, 'americanexpress');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.webnode.Aerified', 'Hudsonian godwit', 'jcb', 'Indigo', 11, 'maestro');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('org.unesco.Holdlamis', 'Bahama pintail', 'maestro', 'Turquoise', 12, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('gov.nasa.Hatity', 'Lapwing, southern', 'maestro', 'Red', 13, 'switch');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.blogger.Bitchip', 'Possum, golden brush-tailed', 'jcb', 'Violet', 14, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.pinterest.Flowdesk', 'Crake, african black', 'mastercard', 'Teal', 15, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('jp.shop-pro.Temp', 'Sandgrouse, yellow-throated', 'diners-club-enroute', 'Goldenrod', 16, 'bankcard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('jp.co.yahoo.Regrant', 'Slender loris', 'jcb', 'Violet', 17, 'china-unionpay');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('it.google.Fix San', 'Dromedary camel', 'jcb', 'Crimson', 18, 'maestro');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.blogs.Ventosanzap', 'Skimmer, four-spotted', 'china-unionpay', 'Red', 19, 'americanexpress');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('org.creativecommons.Quo Lux', 'Possum, pygmy', 'switch', 'Goldenrod', 20, 'bankcard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.paypal.Tin', 'Sandgrouse, yellow-throated', 'mastercard', 'Turquoise', 21, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('net.jalbum.Matsoft', 'Shrike, southern white-crowned', 'jcb', 'Puce', 22, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.wsj.Pannier', 'Great white pelican', 'jcb', 'Fuscia', 23, 'diners-club-enroute');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('cn.google.Hatity', 'Mouflon', 'visa-electron', 'Turquoise', 24, 'mastercard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.barnesandnoble.Opela', 'Squirrel, smith''s bush', 'maestro', 'Teal', 25, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.go.Vagram', 'Asian lion', 'jcb', 'Goldenrod', 26, 'switch');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.lycos.Zoolab', 'Scaly-breasted lorikeet', 'jcb', 'Turquoise', 27, 'visa-electron');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.cbslocal.Bamity', 'Stork, greater adjutant', 'jcb', 'Yellow', 28, 'visa-electron');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('gov.va.Aerified', 'Southern sea lion', 'jcb', 'Maroon', 29, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.forbes.Ronstring', 'American racer', 'china-unionpay', 'Mauv', 30, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.mediafire.Regrant', 'Goose, cape barren', 'mastercard', 'Maroon', 31, 'visa-electron');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.reuters.Tres-Zap', 'Tortoise, desert', 'visa', 'Yellow', 32, 'visa-electron');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('net.clickbank.Namfix', 'Giant girdled lizard', 'jcb', 'Orange', 33, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('cn.gov.miitbeian.Aerified', 'Blesbok', 'mastercard', 'Aquamarine', 34, 'china-unionpay');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.tripadvisor.Toughjoyfax', 'Moorhen, purple', 'visa-electron', 'Puce', 35, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('uk.co.google.Sonsing', 'Pallas''s fish eagle', 'jcb', 'Maroon', 36, 'visa-electron');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.nba.Konklab', 'Marshbird, brown and yellow', 'mastercard', 'Indigo', 37, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.mayoclinic.Asoka', 'Red-legged pademelon', 'maestro', 'Indigo', 38, 'americanexpress');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.soundcloud.Wrapsafe', 'Southern black-backed gull', 'jcb', 'Fuscia', 39, 'switch');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.hao123.Redhold', 'Siskin, pine', 'jcb', 'Puce', 40, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.sun.Namfix', 'Phalarope, northern', 'switch', 'Fuscia', 41, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('gov.epa.Ronstring', 'Hyena, spotted', 'switch', 'Pink', 42, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('fr.unblog.Redhold', 'Raccoon dog', 'jcb', 'Pink', 43, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('jp.ne.hatena.Mat Lam Tam', 'Otter, small-clawed', 'jcb', 'Blue', 44, 'instapayment');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('cc.tiny.Alphazap', 'Yellow-headed caracara', 'mastercard', 'Teal', 45, 'china-unionpay');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('gov.hud.Zathin', 'Flicker, field', 'diners-club-enroute', 'Violet', 46, 'mastercard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('gov.house.Voltsillam', 'Reedbuck, bohor', 'jcb', 'Turquoise', 47, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.hexun.Cookley', 'Kalahari scrub robin', 'jcb', 'Aquamarine', 48, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.microsoft.Matsoft', 'Common shelduck', 'maestro', 'Aquamarine', 49, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('net.ovh.Treeflex', 'African snake (unidentified)', 'diners-club-us-ca', 'Red', 50, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.reference.Alphazap', 'Blue-faced booby', 'diners-club-enroute', 'Khaki', 51, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('edu.illinois.It', 'Gecko, bent-toed', 'jcb', 'Maroon', 52, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.scribd.Transcof', 'Crow, pied', 'americanexpress', 'Turquoise', 53, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('jp.ne.biglobe.Stim', 'Canadian river otter', 'americanexpress', 'Red', 54, 'mastercard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.taobao.It', 'Beisa oryx', 'jcb', 'Goldenrod', 55, 'maestro');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('jp.ne.goo.Tempsoft', 'Phascogale, red-tailed', 'diners-club-enroute', 'Pink', 56, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('org.npr.Keylex', 'White-browed sparrow weaver', 'mastercard', 'Green', 57, 'visa-electron');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.istockphoto.Sub-Ex', 'Mountain duck', 'diners-club-enroute', 'Indigo', 58, 'americanexpress');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('jp.co.rakuten.Asoka', 'Crow, pied', 'diners-club-us-ca', 'Khaki', 59, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('org.networkadvertising.Andalax', 'Southern elephant seal', 'jcb', 'Blue', 60, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.oracle.Zathin', 'Stork, greater adjutant', 'jcb', 'Indigo', 61, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('net.comcast.Treeflex', 'Seal, northern fur', 'bankcard', 'Orange', 62, 'mastercard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('uk.ac.cam.Otcom', 'Black-fronted bulbul', 'jcb', 'Indigo', 63, 'diners-club-enroute');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.livejournal.Fintone', 'Turaco, violet-crested', 'switch', 'Aquamarine', 64, 'bankcard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.weebly.Y-Solowarm', 'Catfish, blue', 'switch', 'Teal', 65, 'laser');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.wiley.Sonair', 'Egyptian cobra', 'jcb', 'Indigo', 66, 'diners-club-enroute');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.barnesandnoble.Job', 'Racer, american', 'visa', 'Crimson', 67, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('ca.cbc.Lotstring', 'European badger', 'jcb', 'Yellow', 68, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('me.flavors.Transcof', 'Coqui partridge', 'bankcard', 'Puce', 69, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('mil.army.Matsoft', 'Madagascar fruit bat', 'jcb', 'Orange', 70, 'solo');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.engadget.Subin', 'Nubian bee-eater', 'bankcard', 'Purple', 71, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.skype.Veribet', 'Squirrel, smith''s bush', 'jcb', 'Violet', 72, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.storify.Otcom', 'Blue catfish', 'jcb', 'Yellow', 73, 'switch');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.blogger.Duobam', 'Gulls (unidentified)', 'mastercard', 'Crimson', 74, 'diners-club-enroute');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.opera.Fix San', 'Western bearded dragon', 'maestro', 'Orange', 75, 'mastercard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('cn.com.people.Opela', 'Golden jackal', 'visa', 'Red', 76, 'switch');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('us.tx.state.It', 'Cockatoo, long-billed', 'switch', 'Purple', 77, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.naver.Subin', 'Four-horned antelope', 'china-unionpay', 'Aquamarine', 78, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('edu.arizona.Transcof', 'Phascogale, brush-tailed', 'mastercard', 'Green', 79, 'switch');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.facebook.Regrant', 'Blue duck', 'jcb', 'Goldenrod', 80, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.paypal.Zoolab', 'Paca', 'americanexpress', 'Maroon', 81, 'switch');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('gov.usda.Bitchip', 'Roadrunner, greater', 'jcb', 'Teal', 82, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.slate.Cookley', 'Fox, bat-eared', 'diners-club-enroute', 'Green', 83, 'solo');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.homestead.Temp', 'Gull, herring', 'laser', 'Maroon', 84, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('es.google.Biodex', 'Hyena, spotted', 'switch', 'Puce', 85, 'china-unionpay');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('org.edublogs.Toughjoyfax', 'Kingfisher, white-throated', 'jcb', 'Maroon', 86, 'mastercard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.theglobeandmail.Matsoft', 'Brown hyena', 'china-unionpay', 'Violet', 87, 'visa');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('net.a8.Lotstring', 'Shrew, mandras tree', 'visa-electron', 'Blue', 88, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('jp.japanpost.Namfix', 'Pheasant, common', 'maestro', 'Puce', 89, 'instapayment');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.flickr.Mat Lam Tam', 'Macaw, red and blue', 'jcb', 'Khaki', 90, 'diners-club-enroute');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.wp.Matsoft', 'Albatross, waved', 'jcb', 'Teal', 91, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.mayoclinic.Solarbreeze', 'Beisa oryx', 'jcb', 'Goldenrod', 92, 'maestro');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('jp.i2i.Fintone', 'Land iguana', 'diners-club-enroute', 'Puce', 93, 'instapayment');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('gov.whitehouse.Bigtax', 'Indian leopard', 'diners-club-us-ca', 'Green', 94, 'americanexpress');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('gov.usda.Keylex', 'Eastern dwarf mongoose', 'mastercard', 'Red', 95, 'diners-club-enroute');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('eu.europa.Regrant', 'Pigeon, wood', 'diners-club-enroute', 'Fuscia', 96, 'mastercard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('edu.illinois.Sub-Ex', 'Butterfly (unidentified)', 'jcb', 'Violet', 97, 'maestro');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.jigsy.Fixflex', 'Steenbok', 'mastercard', 'Green', 98, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.rediff.Overhold', 'Wolf spider', 'maestro', 'Yellow', 99, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('edu.tamu.Matsoft', 'Yak', 'visa', 'Blue', 100, 'mastercard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.bluehost.Temp', 'Snowy sheathbill', 'jcb', 'Puce', 101, 'mastercard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('edu.unc.Sonsing', 'Porcupine, crested', 'solo', 'Yellow', 102, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.purevolume.It', 'Cape starling', 'jcb', 'Teal', 103, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.mapquest.Y-Solowarm', 'Chickadee, black-capped', 'jcb', 'Khaki', 104, 'diners-club-enroute');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('uk.co.bbc.Biodex', 'Marabou stork', 'visa', 'Maroon', 105, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.nydailynews.Regrant', 'Fox, grey', 'jcb', 'Green', 106, 'diners-club-enroute');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('cn.gov.miibeian.Matsoft', 'Lion, steller sea', 'diners-club-carte-blanche', 'Violet', 107, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.mtv.Zoolab', 'Sally lightfoot crab', 'china-unionpay', 'Orange', 108, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('gd.is.Konklab', 'Seal, southern elephant', 'diners-club-carte-blanche', 'Violet', 109, 'mastercard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.ibm.Tampflex', 'Tree porcupine', 'jcb', 'Goldenrod', 110, 'maestro');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.baidu.Latlux', 'Vulture, white-headed', 'china-unionpay', 'Orange', 111, 'mastercard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.alexa.Transcof', 'Black-backed jackal', 'jcb', 'Teal', 112, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('it.tuttocitta.Alpha', 'Long-tailed skua', 'americanexpress', 'Blue', 113, 'china-unionpay');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.reference.Sonair', 'Black spider monkey', 'china-unionpay', 'Green', 114, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.qq.Mat Lam Tam', 'Campo flicker', 'jcb', 'Violet', 115, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('ru.narod.Keylex', 'Indian star tortoise', 'jcb', 'Teal', 116, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('au.org.auda.Sub-Ex', 'Gemsbok', 'jcb', 'Yellow', 117, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.youtube.Stim', 'Black-crowned night heron', 'americanexpress', 'Green', 118, 'switch');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.cargocollective.It', 'Lizard (unidentified)', 'switch', 'Yellow', 119, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.livejournal.Domainer', 'Four-striped grass mouse', 'jcb', 'Orange', 120, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.naver.Fixflex', 'Goat, mountain', 'jcb', 'Puce', 121, 'diners-club-enroute');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.cnbc.Otcom', 'Langur, hanuman', 'jcb', 'Orange', 122, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.mac.Fintone', 'White-throated kingfisher', 'jcb', 'Yellow', 123, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.bandcamp.Zamit', 'Eagle, tawny', 'mastercard', 'Green', 124, 'bankcard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.sfgate.Rank', 'Square-lipped rhinoceros', 'solo', 'Purple', 125, 'instapayment');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.tripadvisor.Zathin', 'Mongoose, javan gold-spotted', 'jcb', 'Goldenrod', 126, 'diners-club-international');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.nationalgeographic.Daltfresh', 'Lizard, goanna', 'jcb', 'Blue', 127, 'instapayment');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.zimbio.Solarbreeze', 'White-throated robin', 'diners-club-carte-blanche', 'Khaki', 128, 'maestro');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.tmall.Toughjoyfax', 'Lizard, mexican beaded', 'laser', 'Red', 129, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.ask.Bitwolf', 'Savanna fox', 'americanexpress', 'Aquamarine', 130, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.blogs.Span', 'Moorhen, purple', 'jcb', 'Fuscia', 131, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.soundcloud.Ronstring', 'Partridge, coqui', 'jcb', 'Violet', 132, 'instapayment');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.nytimes.Zontrax', 'European red squirrel', 'jcb', 'Crimson', 133, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.weibo.Lotlux', 'Squirrel, indian giant', 'jcb', 'Blue', 134, 'mastercard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.mayoclinic.Tres-Zap', 'Shelduck, common', 'americanexpress', 'Aquamarine', 135, 'switch');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('org.simplemachines.Sonsing', 'Javanese cormorant', 'china-unionpay', 'Khaki', 136, 'mastercard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.globo.Redhold', 'Turkey, common', 'jcb', 'Pink', 137, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.fastcompany.Aerified', 'Bengal vulture', 'jcb', 'Aquamarine', 138, 'visa-electron');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.mysql.Toughjoyfax', 'Springbuck', 'jcb', 'Green', 139, 'visa-electron');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('edu.mit.Latlux', 'Cheetah', 'switch', 'Indigo', 140, 'china-unionpay');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('net.discuz.Rank', 'Trumpeter swan', 'laser', 'Violet', 141, 'china-unionpay');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('edu.mit.Vagram', 'Scaly-breasted lorikeet', 'jcb', 'Aquamarine', 142, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.discovery.Home Ing', 'Caracal', 'jcb', 'Aquamarine', 143, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.oakley.Pannier', 'Parakeet, rose-ringed', 'jcb', 'Teal', 144, 'instapayment');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('au.com.google.Alpha', 'Flamingo, roseat', 'mastercard', 'Teal', 145, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.list-manage.Zoolab', 'Cardinal, red-capped', 'maestro', 'Indigo', 146, 'diners-club-international');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('it.tuttocitta.Lotlux', 'Buffalo, american', 'jcb', 'Green', 147, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.wikispaces.Treeflex', 'Albatross, waved', 'mastercard', 'Red', 148, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.bloglines.Y-Solowarm', 'Common green iguana', 'mastercard', 'Indigo', 149, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.reverbnation.Sonair', 'Otter, african clawless', 'maestro', 'Red', 150, 'switch');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.vistaprint.Zoolab', 'Neotropic cormorant', 'diners-club-enroute', 'Maroon', 151, 'switch');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('org.gmpg.Lotstring', 'Asian elephant', 'switch', 'Mauv', 152, 'diners-club-us-ca');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('gov.whitehouse.Sonsing', 'Dragon, western bearded', 'jcb', 'Green', 153, 'mastercard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.com.Lotlux', 'Suricate', 'diners-club-enroute', 'Orange', 154, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.jigsy.Temp', 'Gecko (unidentified)', 'jcb', 'Crimson', 155, 'diners-club-carte-blanche');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('io.github.Ronstring', 'Cuis', 'jcb', 'Teal', 156, 'mastercard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('co.t.Zamit', 'Egyptian cobra', 'jcb', 'Aquamarine', 157, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.myspace.Bitchip', 'Skink, african', 'switch', 'Teal', 158, 'diners-club-enroute');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.quantcast.Subin', 'Duiker, common', 'jcb', 'Fuscia', 159, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.163.Treeflex', 'Dove, galapagos', 'maestro', 'Indigo', 160, 'diners-club-carte-blanche');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('org.simplemachines.Vagram', 'Squirrel, malabar', 'jcb', 'Goldenrod', 161, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('org.archive.Subin', 'Australian sea lion', 'americanexpress', 'Goldenrod', 162, 'maestro');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.omniture.Greenlam', 'Beaver, american', 'jcb', 'Yellow', 163, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('pl.google.Mat Lam Tam', 'Rock dove', 'jcb', 'Purple', 164, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.purevolume.Zaam-Dox', 'African clawless otter', 'bankcard', 'Khaki', 165, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.indiegogo.Konklab', 'South African hedgehog', 'jcb', 'Goldenrod', 166, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.ihg.Zaam-Dox', 'Azara''s zorro', 'jcb', 'Blue', 167, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.cloudflare.Job', 'South African hedgehog', 'maestro', 'Orange', 168, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.deliciousdays.Zoolab', 'Barbet, crested', 'jcb', 'Red', 169, 'visa');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.topsy.Kanlam', 'Otter, cape clawless', 'mastercard', 'Fuscia', 170, 'bankcard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.hao123.Sub-Ex', 'Marmot, yellow-bellied', 'jcb', 'Maroon', 171, 'diners-club-carte-blanche');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.nature.Sonsing', 'Thrasher, curve-billed', 'jcb', 'Orange', 172, 'switch');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('org.dmoz.Veribet', 'Miner''s cat', 'jcb', 'Purple', 173, 'diners-club-carte-blanche');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.java.Job', 'Grey lourie', 'jcb', 'Purple', 174, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.chron.Treeflex', 'Cat, tiger', 'diners-club-international', 'Puce', 175, 'diners-club-carte-blanche');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('uk.co.webeden.Duobam', 'Whale, southern right', 'mastercard', 'Purple', 176, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.nba.Flexidy', 'Wolf spider', 'diners-club-enroute', 'Purple', 177, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.xinhuanet.Prodder', 'Numbat', 'diners-club-enroute', 'Yellow', 178, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.delicious.Zathin', 'Nile crocodile', 'maestro', 'Orange', 179, 'diners-club-carte-blanche');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.shutterfly.Tempsoft', 'Blue and yellow macaw', 'jcb', 'Khaki', 180, 'mastercard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('org.wordpress.Zamit', 'Small-spotted genet', 'jcb', 'Puce', 181, 'mastercard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.icq.Matsoft', 'Yellow mongoose', 'mastercard', 'Turquoise', 182, 'diners-club-carte-blanche');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.slate.Ronstring', 'Thirteen-lined squirrel', 'maestro', 'Yellow', 183, 'mastercard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.delicious.Veribet', 'Opossum, american virginia', 'jcb', 'Orange', 184, 'switch');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('cz.mapy.Greenlam', 'Mexican boa', 'jcb', 'Indigo', 185, 'diners-club-enroute');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('gov.loc.Sonair', 'Blue and yellow macaw', 'laser', 'Goldenrod', 186, 'maestro');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.deviantart.Flowdesk', 'Rhea, greater', 'visa', 'Indigo', 187, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.hp.Daltfresh', 'Falcon, peregrine', 'diners-club-international', 'Pink', 188, 'diners-club-enroute');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('cn.gov.miibeian.Aerified', 'Starling, red-shouldered glossy', 'diners-club-enroute', 'Indigo', 189, 'diners-club-enroute');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('gov.hhs.Zathin', 'Javanese cormorant', 'jcb', 'Purple', 190, 'mastercard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.jigsy.Fintone', 'Dragon, western bearded', 'maestro', 'Aquamarine', 191, 'visa');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('org.dyndns.It', 'Eastern cottontail rabbit', 'jcb', 'Blue', 192, 'china-unionpay');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.lycos.Treeflex', 'Common genet', 'mastercard', 'Turquoise', 193, 'mastercard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.webs.Biodex', 'Asian elephant', 'diners-club-enroute', 'Green', 194, 'solo');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.elegantthemes.Daltfresh', 'Possum, common brushtail', 'jcb', 'Puce', 195, 'visa-electron');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.fc2.Cookley', 'Kori bustard', 'bankcard', 'Crimson', 196, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('gov.epa.Matsoft', 'Waxbill, blue', 'jcb', 'Crimson', 197, 'mastercard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.blogspot.Daltfresh', 'Cat, kaffir', 'bankcard', 'Pink', 198, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.devhub.Daltfresh', 'Tammar wallaby', 'jcb', 'Fuscia', 199, 'bankcard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.foxnews.Cardguard', 'Eagle, long-crested hawk', 'jcb', 'Fuscia', 200, 'diners-club-enroute');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.statcounter.Tresom', 'African polecat', 'visa', 'Khaki', 201, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.histats.Fintone', 'Dragon, netted rock', 'diners-club-enroute', 'Maroon', 202, 'bankcard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('uk.co.bbc.Redhold', 'Squirrel, antelope ground', 'maestro', 'Goldenrod', 203, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.surveymonkey.Job', 'Malabar squirrel', 'maestro', 'Teal', 204, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('de.1und1.Otcom', 'Stork, white-necked', 'mastercard', 'Maroon', 205, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('gl.goo.Sonair', 'Jackal, asiatic', 'laser', 'Teal', 206, 'bankcard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.vistaprint.Namfix', 'Mongoose, javan gold-spotted', 'visa', 'Indigo', 207, 'mastercard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.blogtalkradio.Gembucket', 'Bushbuck', 'bankcard', 'Purple', 208, 'americanexpress');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.prweb.Voyatouch', 'Spider, wolf', 'mastercard', 'Goldenrod', 209, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.delicious.Rank', 'Reedbuck, bohor', 'mastercard', 'Khaki', 210, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('org.prlog.Namfix', 'Tsessebe', 'bankcard', 'Pink', 211, 'mastercard');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('net.cpanel.Namfix', 'Turtle, snake-necked', 'jcb', 'Mauv', 212, 'diners-club-carte-blanche');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('eu.europa.Tampflex', 'Gulls (unidentified)', 'diners-club-us-ca', 'Fuscia', 213, 'switch');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('io.soup.Mat Lam Tam', 'Marshbird, brown and yellow', 'jcb', 'Green', 214, 'diners-club-international');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('gov.ca.Kanlam', 'Glossy ibis', 'americanexpress', 'Mauv', 215, 'switch');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.slate.Biodex', 'Goat, mountain', 'jcb', 'Orange', 216, 'jcb');
insert into tb_pet (owner_id, name, type, fur_color, age, body_build ) values ('com.blogspot.Bitchip', 'Royal tern', 'visa-electron', 'Khaki', 217, 'jcb')